# Generated by Django 3.2.5 on 2021-07-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chai',
            options={'verbose_name_plural': 'chai'},
        ),
        migrations.AddField(
            model_name='chai',
            name='email',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
